### ISSUE TITLE
New api version for ingress manifest

### ISSUE THREAD

**Issue by dragonsmith** [anycable/anycable-helm#10]
Old K8s API version for ingress  will be unavailable soon

> extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

Here is a good example what should we do: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/_helpers.tpl#L104-L113

**Comment by nepalez** [comment]
To be fixed in https://github.com/anycable/anycable-helm/pull/11

**Comment by palkan** [comment]
@dragonsmith @nepalez Can we close this?

**Comment by nepalez** [comment]
> @dragonsmith @nepalez Can we close this?

We can
