### ISSUE TITLE
Latest release is ~1 year old

### ISSUE THREAD

**Issue by bopm** [anycable/anycable-helm#13]
Both changes to Chart and recent versions of Anycable are not included in the releases.

**Comment by Envek** [comment]
Hey! Thank you for paying attention. We will release chart version with latest changes needed for AnyCable 1.1 a bit later.

If you want just to upgrade version of AnyCable-Go in your setup (without using new version-specific settings), just change it in your values, you don't need to upgrade chart for that:
```sh
helm upgrade -i anycable-go \
  --namespace anycable-go \
  --set image.tag=1.1.2 \
  anycable/anycable-go
```
(Don't forget to change installation and namespace names accordingly)

**Comment by Envek** [comment]
anycable-go helm chart [v0.5.2](https://github.com/anycable/anycable-helm/releases/tag/anycable-go-0.5.2) for anycable-go 1.1.2 has been released.
