### ISSUE TITLE
Cannot connect to websocket through load balancer

### ISSUE THREAD

**Issue by x8BitRain** [anycable/anycable-helm#15]
Hey, I can't get any connection at all to the websocket through a digitalocean loadbalancer which is being issued certs by cert-manager, no statuses or errors, just won't connect at all. I've verified the pod is running and can contact the anycable websocket from other pods internally.

I tried using the ingress with acme but cert-manager errored with a depreciation message mentioned in https://github.com/anycable/anycable-helm/issues/10
> extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

I tried pointing the anycable.yaml config to use an existing working certificate but was met with errors when trying to contact it internally, not sure if this is directly related to the problem?

>root@app-86b55bc956-jtttx:/tmp# websocat wss://10.244.0.102:2096/live
>websocat: WebSocket SSL error: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify ?>failed:ssl/statem/statem_clnt.c:1915: (IP address mismatch)
>websocat: error running

Ultimately I'm not sure whether this is being caused by misconfiguring TLS or ingresses but the fact I cannot get any connection at all is quite strange considering my rails API is working just fine on 443 and 80 in these configs. Any other configurations I should try or am I facing some kinda bug? Thanks!

load-balancer-svc.yml:

    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
        service.beta.kubernetes.io/do-loadbalancer-hostname: "api.example.com"
        service.beta.kubernetes.io/do-loadbalancer-name: "api.example.com"
        service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
        service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "false"
        service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-ttl: "60"
      labels:
        helm.sh/chart: ingress-nginx-2.11.1
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/instance: ingress-nginx
        app.kubernetes.io/version: 0.34.1
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: controller
      name: ingress-nginx-controller
      namespace: ingress-nginx
    spec:
      type: LoadBalancer
      externalTrafficPolicy: Local
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: http
        - name: https
          port: 443
          protocol: TCP
          targetPort: https
        - name: anycable
          port: 2096
          targetPort: 2096
      selector:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/instance: ingress-nginx
        app.kubernetes.io/component: controller

ingress.yml:

    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: ingress
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.ingress.kubernetes.io/secure-backends: "false"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/websocket-services: "anycable-go-anycable-go"
        nginx.org/websocket-services: "anycable-go-anycable-go"
    spec:
      tls:
        - hosts:
            - api.example.to
          secretName: example-kubernetes-tls
      rules:
        - host: "api.example.com"
          http:
            paths:
              - path: "/"
                pathType: Prefix
                backend:
                  service:
                    name: app
                    port:
                      number: 3000
              - path: "/v1"
                pathType: Prefix
                backend:
                  service:
                    name: app
                    port:
                      number: 3000
              - path: "/live"
                pathType: Prefix
                backend:
                  service:
                    name: anycable-go-anycable-go
                    port:
                      number: 2096

anycable-go.yml

    nodeSelector: {}
    replicas: 1
    image:
      repository: anycable/anycable-go
      tag: 1.0.2
      pullPolicy: IfNotPresent
    
    revisionHistoryLimit: 10
    
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
      
    resources:
      limits:
        cpu: 100m
        memory: 400Mi
      requests:
        cpu: 100m
        memory: 400Mi
    
    serviceMonitor:
      enabled: false
      labels: {}
    
    tls:
      secretName: "example-kubernetes-tls"
    
    env:
      anycableHost: "0.0.0.0"
      anycablePort: "2096"
      anycablePath: "/live"
      anycableRedisUrl: redis://redis:6379/0
      anycableRedisChannel: "__anycable__"
      anycableRedisSentinels: ""
      anycableRedisSentinelDiscoveryInterval: "30"
      anycableRedisKeepaliveInterval: ""
      anycableRpcHost: rpc:50051
      anycableHeaders: "cookie"
      anycableDisconnectRate: "100"
      anycableLogLevel: "debug"
      anycableLogFormat: "text"
      anycableDebug: "true"
      anycableMetricsLog: ""
      anycableMetricsLogInterval: "15"
      anycableMetricsLogFormatter: ""
      anycableMetricsHttp: "/metrics"
      anycableMetricsHost: ""
      anycableMetricsPort: "2097"
      anycableHealthPath: "/health"
      anycableMaxMessageSize: ""

**Comment by palkan** [comment]
Could you please provide logs for anycable-go service? And ingress logs could be helpful as well.

@Envek Any guesses?

**Comment by x8BitRain** [comment]
@palkan Anycable in debug mode does not produce any logs beyond the normal initialization messages because it never receives any connections.
Unfortunately I've removed the cluster and the ingress so I have no ingress logs to show but maybe you can help me better understand how to set this up from a higher level.

What is the best strategy for running anycable in a cluster? When I configure anycable to run with an ingress it sets up a separate ingress that seems to not work properly with or without acme,
> extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

is mentioned in cert-manager when I configure it with acme. Is the intention of the ingress configuration for it to create it's own separate ingress or apply its rules to an existing one, idea I wanted it to work with an existing ingress. I'm not quite clear on this part.

If anycable is configured to run WITH SSL while the load balancer is also config'd with SSL, do I use the same certs or issue separate ones? How is the load balancer supposed to be configured? Should TCP passthrough be enabled or something else? Or should I run anycable without SSL and terminate SSL at the load balancer and proxy pass the request to the anycable service? What do you recommend? Thanks.

**Comment by Envek** [comment]
I think the problem here is that we have hardcoded port number at service level to 80: https://github.com/anycable/anycable-helm/blob/f30c6e8e6ca6b812ff1a7b035fe82f09ad239977/anycable-go/templates/service.yml#L12-L15

While we're referring to pod's port (which is configured by `env.anycablePort` value) by name `http`,
**right now ingress MUST refer to service port by exact value of `80`.**

I believe that this is the reason.

So you either need to change your ingress definition as follows:

```diff
           - path: "/live"
             pathType: Prefix
             backend:
               service:
                 name: anycable-go-anycable-go
                 port:
-                  number: 2096
+                  number: 80
```

Please check and let us know whether it worked!

**Or** you can use our bundled ingress instead, providing DO-specific annotations to it through values, like this:

```yaml
# Configuration for the dependent Helm chart "anycable/anycable-go"
anycable-go:
  env:
    anycableRedisUrl: redis://redis/0
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/secure-backends: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/websocket-services: "anycable-go-anycable-go"
      nginx.org/websocket-services: "anycable-go-anycable-go"
    enable: true
    path: /live
```

In any case we usually terminate SSL at Ingress, and keep communication between ingress and anycable-go unencrypted (so you need to use `ws://` protocol with `websocat` when accessing anycable pod directly and not `wss://`).
