### ISSUE TITLE
Taints and tolerations

### ISSUE THREAD

**Issue by vitobotta** [anycable/anycable-helm#28]
Hi! is it possible somehow to configure tolerations so that I can run AnyCable on spot instances for dev clusters? We run almost everything else on spot instances and scale to zero when unused in dev clusters. Thanks!

**Comment by vitobotta** [comment]
@nepalez @dragonsmith Hi! I see you assigned this. Any update? Thanks! :)

**Comment by nepalez** [comment]
Hey @vitobotta 
Thank you for the suggestion
I added tolerations in v0.5.6

**Comment by vitobotta** [comment]
This is awesome, thanks @nepalez ! I will try it as soon as I can.
