### ISSUE TITLE
Tag 1.2.4 - anycable-go:1.2.4: not found

### ISSUE THREAD

**Issue by nileshm2501** [anycable/anycable-helm#37]
Hi Team,

Getting image tag not found, Can you pls check and update the default tag. Checked in the docker repo as well, and it seems 1.2.4 tag is removed.

`Warning  Failed     52m (x4 over 53m)      kubelet            Failed to pull image "anycable/anycable-go:1.2.4": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/anycable/anycable-go:1.2.4": failed to resolve reference "docker.io/anycable/anycable-go:1.2.4": docker.io/anycable/anycable-go:1.2.4: not found`

**Comment by nepalez** [comment]
[Fixed](https://github.com/anycable/anycable-helm/commit/1aa3091cb27ce00d1f01d70ed78d52186cbde2db#diff-fc09f61b94b0f447d37d450a93770e4e4c1578bd6187b541d166f481746f3806R14) by @dragonsmith at [v0.5.9](https://github.com/anycable/anycable-helm/releases/tag/anycable-go-0.5.9)
